---
- name: import assert.yml
  import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

# Ensure that the key pair exists
# Note This task fails for .pem files

# - name: Find or create EC2 Key pair
#   ec2_key:
#     state: present
#     region: "{{ aws_vpc.region }}"
#     name: "{{ nat_key_path | basename | splitext | first }}"
#     key_material: "{{ lookup('file', nat_key_path) }}"
#   delegate_to: localhost

- name: create NAT security group
  amazon.aws.ec2_group:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_vpc.region }}"
    name: "{{ nat_sg_name }}"
    description: NAT-VPN security group
    purge_rules: no
    purge_rules_egress: no
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "{{ wg_listen_port }}"
        to_port: "{{ wg_listen_port }}"
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  delegate_to: localhost

- name: create the NAT instance
  amazon.aws.ec2_instance:
    name: "{{ nat_name }}"
    region: "{{ aws_vpc.region }}"
    image_id: "{{ nat_ami_id }}"
    instance_type: "{{ nat_mach_type }}"
    key_name: "{{ nat_key_name }}"
    vpc_subnet_id: "{{ subnet_id_map[nat_subnet_name] }}"
    security_group: "{{ nat_sg_name }}"
    state: running
    network:
      assign_public_ip: false
      source_dest_check: false
    wait: true
  register: nat_result

- name: allocate an elastic IP
  community.aws.ec2_eip:
    in_vpc: true
    device_id: "{{ nat_result.instance_ids[0] }}"
    region: "{{ aws_vpc.region }}"
    reuse_existing_ip_allowed: yes
    tag_name: "Eip"
    tag_value: "wireguard"
  register: eip

- name: debug eip
  debug: var=eip

- name: Add routing rule for NAT egress into our internal gateway
  community.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_vpc.region }}"
    purge_routes: false
    purge_subnets: false
    lookup: id
    route_table_id: "{{ rt_priv_id }}"
    routes:
      - dest: 0.0.0.0/0
        instance_id: "{{ nat_result.instance_ids[0] }}"

- name: wait for ssh to come up
  ansible.builtin.wait_for:
    port: 22
    host: "{{ eip.public_ip }}"
    delay: 60
    timeout: 300
  delegate_to: localhost

- name: Add host to wireguard group
  add_host:
    name: "{{ eip.public_ip }}"
    ansible_user: "{{ nat_user_name }}"
    ansible_ssh_private_key_file: "{{ nat_key_path }}"
    groups:
      - wireguard
